name: Deploy to neocities

on:
  push:
    branches:
      - master

concurrency:
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: python3 generate_site.py -J "$json"
        env:
          json: '{ "host": { "name": "selfhosted", "badge": { "href": "https://www.lighttpd.net/", "src":"lighttpd.png", "alt": "selfhosted using lighttpd" } } }'
      - name: Install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H lanikjo.org > ~/.ssh/known_hosts
      - name: Deploy to VPS
        run: rsync -vrl --progress --delete ./deploy/ lanikjo@lanikjo.org:/var/www/deploy
      - run: python3 generate_site.py
      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v2
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          dist_dir: deploy
      - name: Cleanup ssh
        run: rm -rf ~/.ssh 
